name: Go Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  GOCACHE: "/tmp/go-cache"
  GOMODCACHE: "/tmp/go-mod-cache"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Display Go version
        run: go version

      - name: Go test
        run: |
          go test \
          -cover -coverprofile=unit.coverage.out \
          github.com/robbyt/go-supervisor/runnables/... \
          github.com/robbyt/go-supervisor/supervisor/...
      
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: unit.coverage.out
          force-coverage-parser: go

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.language: go
            -Dsonar.sourceEncoding: UTF-8
            -Dsonar.go.coverage.reportPaths: unit.coverage.out